### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#12]
- [x] 曲検索
- [x] 統計
- [x] 管理者の追加・削除
- [x] 管理者によるディアクティベート
- [x] プロフィールの公開範囲
- [x] 曲の公開範囲
- [x] プロフィール項目を増やす
- [x] リリース
- [x] Analytics と Adsense を仕込む
- [x] SSL 対応
- [x] README ちゃんと書く
- [x] パスワードの変更
- [ ] テストをしっかり書く
- [ ] アルバムURLをライブに追加（入部1年前から8年間のみ閲覧可）
- [ ] 曲の個別ページを Modal にする（show アクションで .js フォーマットに対応する）
